#!/bin/sh -e

export PREFIX=""
UNAME=$(uname)
case "$UNAME" in
"Linux") export SYSTEM="Linux" ;;
"Darwin") export SYSTEM="Linux" ;;
CYGWIN*) export SYSTEM="Windows" ;;
MINGW*) export SYSTEM="Windows" ;;
*) export SYSTEM="Linux" ;;
esac

if [ -d 'venv' ]; then
  if [ $SYSTEM = "Linux" ] ; then
    export PREFIX="venv/bin/"
  else
    export PREFIX="venv/Scripts/"
  fi
fi

export SOURCE_FILES="databases tests"

set -x

${PREFIX}isort --check --diff --project=databases $SOURCE_FILES
${PREFIX}black --check --diff $SOURCE_FILES
${PREFIX}mypy databases
