#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi
export SOURCE_FILES="databases tests"

set -x

${PREFIX}isort --check --diff --project=databases $SOURCE_FILES
${PREFIX}black --check --diff $SOURCE_FILES
${PREFIX}mypy databases
