#!/bin/sh -e

if [ -d 'dist' ] ; then
    rm -r dist
fi
if [ -d 'site' ] ; then
    rm -r site
fi
if [ -d 'databases.egg-info' ] ; then
    rm -r databases.egg-info
fi

find databases -type f -name "*.py[co]" -delete
find databases -type d -name __pycache__ -delete
