#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

if [ -z $GITHUB_ACTIONS ]; then
    ${PREFIX}coverage report --show-missing --skip-covered --fail-under=100
else
    ${PREFIX}coverage combine
    ${PREFIX}coverage report --show-missing --skip-covered --fail-under=100
fi


